LOCK TABLES `data_platform_ex_conf_api_mapper_data` WRITE;

INSERT INTO `data_platform_ex_conf_api_mapper_data` (`APIServiceName`, `APIType`, `APIName`,`Field`, `ExConfAPIServiceName`, `Tabletag`, `TableConfirmed`, `ExConfAPIType`)
VALUES
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_Header', 'BusinessPartner', 'DPFM_API_BUSINESS_PARTNER_SRV', 'BusinessPartnerGeneral', 'data-platform-business-partner-general-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_Header', 'DistributionChannel', 'DPFM_API_DISTRIBUTION_CHANNEL_SRV', 'DistributionChannel', 'data-platform-distribution-channel-distribution-channel-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_Header', 'Division', 'DPFM_API_DIVISION_SRV', 'Division', 'data-platform-division-division-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_Header', 'District', 'DPFM_API_DISTRICT_SRV', 'District', 'data-platform-district-district-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_Header', 'Language', 'DPFM_API_LANGUAGE_SRV', 'Language', 'data-platform-language-language-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_Header', 'Customer', 'DPFM_API_BUSINESS_PARTNER_SRV_CUSTOMER', 'BusinessPartnerCustomer', 'data-platform-business-partner-customer-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_Header', 'Supplier', 'DPFM_API_BUSINESS_PARTNER_SRV_SUPPLIER', 'BusinessPartnerSupplier', 'data-platform-business-partner-supplier-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_Header', 'TransactionCurrency', 'DPFM_API_CURRENCY_SRV', 'Currency', 'data-platform-currency-currency-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_Header', 'Incoterms', 'DPFM_API_INCOTERMS_SRV', 'Incoterms', 'data-platform-incoterms-incoterms-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_Header', 'PaymentTerms', 'DPFM_API_PAYMENT_TERMS_SRV', 'PaymentTerms', 'data-platform-payment-terms-payment-terms-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_Header', 'PaymentMethod', 'DPFM_API_PAYMENT_METHOD_SRV', 'PaymentMethod', 'data-platform-payment-method-payment-method-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_HeaderPartner', 'PartnerFunction', 'DPFM_API_PARTNER_FUNCTION_SRV', 'PartnerFunction', 'data-platform-partner-function-sql-partner-function-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_HeaderPartner', 'BusinessPartner', 'DPFM_API_BUSINESS_PARTNER_SRV', 'BusinessPartnerGeneral', 'data-platform-business-partner-general-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_HeaderPartner', 'Plant', 'DPFM_API_PLANT_SRV', 'PlantGeneral', 'data-platform-plant-general-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_HeaderPartner', 'Language', 'DPFM_API_LANGUAGE_SRV', 'Language', 'data-platform-language-language-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_HeaderPartner', 'Currency', 'DPFM_API_CURRENCY_SRV', 'Currency', 'data-platform-currency-currency-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_ItemPartner', 'PartnerFunction', 'DPFM_API_PARTNER_FUNCTION_SRV', 'PartnerFunction', 'data-platform-partner-function-sql-partner-function-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_ItemPartner', 'BusinessPartner', 'DPFM_API_BUSINESS_PARTNER_SRV', 'BusinessPartnerGeneral', 'data-platform-business-partner-general-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_HeaderPartnerPlant', 'Plant', 'DPFM_API_PLANT_SRV', 'PlantGeneral', 'data-platform-plant-general-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_HeaderPDF', 'DocIssuerBusinessPartner', 'DPFM_API_BUSINESS_PARTNER_SRV', 'BusinessPartnerGeneral', 'data-platform-business-partner-general-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_Address', 'PostalCode', 'DPFM_API_POSTAL_CODE_SRV', 'PostalCode', 'data-platform-postal-code-sql-postal-code-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_Address', 'LocalRegion', 'DPFM_API_LOCAL_REGION_SRV', 'LocalRegion', 'data-platform-local-region-sql-local-region-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_Address', 'Country', 'DPFM_API_COUNTRY_SRV', 'Country', 'data-platform-country-sql-country-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_Address', 'District', 'DPFM_API_DISTRICT_SRV', 'District', 'data-platform-district-sql-district-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_Address', 'District', 'DPFM_API_DISTRICT_SRV', 'District', 'data-platform-district-sql-district-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_Item', 'Product', 'DPFM_API_PRODUCT_MASTER_SRV', 'ProductGeneral', 'data-platform-product-master-sql-general-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_Item', 'StockConfirmationPartnerFunction', 'DPFM_API_PARTNER_FUNCTION_SRV', 'PartnerFunction', 'data-platform-partner-function-sql-partner-function-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_Item', 'StockConfirmationBusinessPartner', 'DPFM_API_BUSINESS_PARTNER_SRV', 'BusinessPartnerGeneral', 'data-platform-business-partner-general-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_Item', 'StockConfirmationPlant', 'DPFM_API_PLANT_SRV', 'PlantGeneral', 'data-platform-plant-general-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_Item', 'StockConfirmationPlantBatch', 'DPFM_API_BATCH_MASTER_RECORD_SRV', 'Batch', 'data-platform-batch-master-record-sql-batch-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_Item', 'StockConfirmationPolicy', 'DPFM_API_SUPPLY_CHAIN_RELATIONSHIP_SRV', 'SupplyChainRealtionship', 'data-platform-supply-chain-relationship-sql-supply-chain-relationship-data.sql', 'exconf')
    ('DPFM_API_ORDERS_SRV', 'creates', 'A_Item', 'ItemWeightUnit', 'DPFM_API_QUANTITY_UNIT_SRV', 'QuantityUnit', 'data-platform-quantity-unit-sql-quantity-unit-data.sql', 'exconf')
UNLOCK TABLES;