LOCK TABLES `data_platform_ex_conf_api_mapper_data` WRITE;

INSERT INTO `data_platform_ex_conf_api_mapper_data` (`ServiceLabel`, `APIType`, `APIName`,`Field`, `ExConfAPIServiceName`, `ExConfAPIName`, `ExConfAPIQueueName`, `Tabletag`, `TableConfirmed`, `ExConfAPIType`)
VALUES
	('ORDERS', 'creates', 'Address', 'Address', 'DPFM_API_ADDRESS_SRV', 'data_platform_api_address_exconf', 'data_platform_api_address_exconf_queue', 'Address', 'data_platform_address_address_data', 'exconf');
	('ORDERS', 'creates', 'Header', 'BillFromParty', 'DPFM_API_BUSINESS_PARTNER_SRV', 'data_platform_api_business_partner_exconf', 'BusinessPartnerGeneral', 'data_platform_business_partner_general_data', 'exconf');
	('ORDERS', 'creates', 'Heade', 'BillToParty', 'DPFM_API_BUSINESS_PARTNER_SRV', 'data_platform_api_business_partner_exconf', 'BusinessPartnerGeneral', 'data_platform_business_partner_general_data', 'exconf');
	('ORDERS', 'creates', 'Header', 'Buyer', 'DPFM_API_BUSINESS_PARTNER_SRV', 'data_platform_api_business_partner_exconf', 'BusinessPartnerGeneral', 'data_platform_business_partner_general_data', 'exconf');
	('ORDERS', 'creates', 'Header', 'Currency', 'DPFM_API_CURRENCY_SRV', 'data_platform_api_currency_exconf', 'Currency', 'data_platform_currency_currency_data', 'exconf');
	('ORDERS', 'creates', 'Header', 'Incoterms', 'DPFM_API_INCOTERMS_SRV', 'data_platform_api_incoterms_exconf', 'Incoterms', 'data_platform_incoterms_incoterms_data', 'exconf');
	('ORDERS', 'creates', 'Header', 'Payee', 'DPFM_API_BUSINESS_PARTNER_SRV', 'data_platform_api_business_partner_exconf', 'BusinessPartnerGeneral', 'data_platform_business_partner_general_data', 'exconf');
	('ORDERS', 'creates', 'Header', 'Payer', 'DPFM_API_BUSINESS_PARTNER_SRV', 'data_platform_api_business_partner_exconf', 'BusinessPartnerGeneral', 'data_platform_business_partner_general_data', 'exconf');
	('ORDERS', 'creates', 'Header', 'PaymentMethod', 'DPFM_API_PAYMENT_METHOD_SRV', 'data_platform_api_payment_method_exconf', 'PaymentMethod', 'data_platform_payment_method_payment_method_data', 'exconf');
	('ORDERS', 'creates', 'Header', 'PaymentTerms', 'DPFM_API_PAYMENT_TERMS_SRV', 'data_platform_api_payment_terms_exconf', 'PaymentTerms', 'data_platform_payment_terms_payment_terms_data', 'exconf');
	('ORDERS', 'creates', 'Header', 'Seller', 'DPFM_API_BUSINESS_PARTNER_SRV', 'data_platform_api_business_partner_exconf', 'BusinessPartnerGeneral', 'data_platform_business_partner_general_data', 'exconf');
	('ORDERS', 'creates', 'Header', 'SupplyChainRelationshipBillingID', 'DPFM_API_SUPPLY_CHAIN_RELATIONSHIP_SRV', 'data_platform_api_supply_chain_relationship_exconf', 'SupplyChainRelationshipBillingRelation', 'data_platform_supply_chain_relationship_general_data', 'exconf');
	('ORDERS', 'creates', 'Header', 'SupplyChainRelationshipID', 'DPFM_API_SUPPLY_CHAIN_RELATIONSHIP_SRV', 'data_platform_api_supply_chain_relationship_exconf', 'SupplyChainRelationshipGeneral', 'data_platform_supply_chain_relationship_payment_relation_data', 'exconf');
	('ORDERS', 'creates', 'Header', 'SupplyChainRelationshipPaymentID', 'DPFM_API_SUPPLY_CHAIN_RELATIONSHIP_SRV', 'data_platform_api_supply_chain_relationship_exconf', 'SupplyChainRelationshipPaymentRelation', 'data_platform_supply_chain_relationship_billing_relation_data', 'exconf');
	('ORDERS', 'creates', 'HeaderDoc', 'DocType', 'DPFM_API_DOC_TYPE_SRV', 'data_platform_api_doc_type_exconf', 'DocType', 'data_platform_doc_type_doc_type_data', 'exconf');
	('ORDERS', 'creates', 'HeaderDoc', 'DocIssuerBusinessPartner', 'DPFM_API_BUSINESS_PARTNER_SRV', 'data_platform_api_business_partner_exconf', 'BusinessPartnerGeneral', 'data_platform_business_partner_general_data', 'exconf');
	('ORDERS', 'creates', 'Address', 'PostalCode', 'DPFM_API_POSTAL_CODE_SRV', 'data_platform_api_postal_code_exconf', 'PostalCode', 'data_platform_postal_code_postal_code_data', 'exconf');
	('ORDERS', 'creates', 'Address', 'LocalRegion', 'DPFM_API_LOCAL_REGION_SRV', 'data_platform_api_local_region_exconf', 'LocalRegion', 'data_platform_local_region_local_region_data', 'exconf');
	('ORDERS', 'creates', 'Address', 'Country', 'DPFM_API_COUNTRY_SRV', 'data_platform_api_country_exconf', 'Country', 'data_platform_country_country_data', 'exconf');
	('ORDERS', 'creates', 'Address', 'District', 'DPFM_API_DISTRICT_SRV', 'data_platform_api_district_exconf', 'District', 'data_platform_district_district_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'SupplyChainRelationshipDeliveryID', 'DPFM_API_SUPPLY_CHAIN_RELATIONSHIP_SRV', 'data_platform_api_supply_chain_relationship_exconf', 'SupplyChainRelationshipDeliveryRelation', 'data_platform_supply_chain_relationship_delivery_relation_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'SupplyChainRelationshipDeliveryPlantID', 'DPFM_API_SUPPLY_CHAIN_RELATIONSHIP_SRV', 'data_platform_api_supply_chain_relationship_exconf', 'SupplyChainRelationshipDeliveryPlantRelation', 'data_platform_supply_chain_relationship_delivery_plant_relation_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'SupplyChainRelationshipStockConfPlantID', 'DPFM_API_SUPPLY_CHAIN_RELATIONSHIP_SRV', 'data_platform_api_supply_chain_relationship_exconf', 'SupplyChainRelationshipStockConfPlantRelation', 'data_platform_supply_chain_relationship_stock_conf_plant_relation_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'SupplyChainRelationshipProductionPlantID', 'DPFM_API_SUPPLY_CHAIN_RELATIONSHIP_SRV', 'data_platform_api_supply_chain_relationship_exconf', 'SupplyChainRelationshipProductionPlantRelation', 'data_platform_supply_chain_relationship_production_plant_relation_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'Product', 'DPFM_API_PRODUCT_MASTER_SRV', 'data_platform_api_product_master_exconf', 'ProductGeneral', 'data_platform_product_master_general_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'ProductStandardID', 'DPFM_API_PRODUCT_MASTER_SRV', 'data_platform_api_product_master_exconf', 'ProductGeneral', 'data_platform_product_master_general_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'ProductGroup', 'DPFM_API_PRODUCT_GROUP_SRV', 'data_platform_api_product_group_exconf', 'ProductGroup', 'data_platform_product_group_product_group_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'BaseUnit', 'DPFM_API_QUANTITY_UNIT_SRV', 'data_platform_api_quantity_unit_exconf', 'QuantityUnit', 'data_platform_quantity_unit_quantity_unit_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'DeliverToParty', 'DPFM_API_BUSINESS_PARTNER_SRV', 'data_platform_api_business_partner_exconf', 'BusinessPartnerGeneral', 'data_platform_business_partner_general_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'DeliverFromParty', 'DPFM_API_BUSINESS_PARTNER_SRV', 'data_platform_api_business_partner_exconf', 'BusinessPartnerGeneral', 'data_platform_business_partner_general_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'DeliverToPlant', 'DPFM_API_PLANT_SRV', 'data_platform_api_plant_exconf', 'PlantGeneral', 'data_platform_plant_general_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'DeliverToPlantStorageLocation', 'DPFM_API_PLANT_SRV', 'data_platform_api_plant_exconf', 'PlantStorageLocation', 'data_platform_plant_storage_location_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'DeliverToPlantBatch', 'DPFM_API_BATCH_MASTER_RECORD_SRV', 'data_platform_api_batch_master_record_exconf', 'Batch', 'data_platform_batch_master_record_batch_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'DeliverFromPlant', 'DPFM_API_PLANT_SRV', 'data_platform_api_plant_exconf', 'PlantGeneral', 'data_platform_plant_general_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'DeliverFromPlantStorageLocation', 'DPFM_API_PLANT_SRV', 'data_platform_api_plant_exconf', 'PlantStorageLocation', 'data_platform_plant_storage_location_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'DeliverFromPlantBatch', 'DPFM_API_BATCH_MASTER_RECORD_SRV', 'data_platform_api_batch_master_record_exconf', 'Batch', 'data_platform_batch_master_record_batch_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'DeliveryUnit', 'DPFM_API_QUANTITY_UNIT_SRV', 'data_platform_api_quantity_unit_exconf', 'QuantityUnit', 'data_platform_quantity_unit_quantity_unit_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'StockConfirmationBusinessPartner', 'DPFM_API_BUSINESS_PARTNER_SRV', 'data_platform_api_business_partner_exconf', 'BusinessPartnerGeneral', 'data_platform_business_partner_general_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'StockConfirmationPlant', 'DPFM_API_PLANT_SRV', 'data_platform_api_plant_exconf', 'PlantGeneral', 'data_platform_plant_general_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'StockConfirmationPlantBatch', 'DPFM_API_BATCH_MASTER_RECORD_SRV', 'data_platform_api_batch_master_record_exconf', 'Batch', 'data_platform_batch_master_record_batch_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'ItemWeightUnit', 'DPFM_API_QUANTITY_UNIT_SRV', 'data_platform_api_quantity_unit_exconf', 'QuantityUnit', 'data_platform_quantity_unit_quantity_unit_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'ProductionPlantBusinessPartner', 'DPFM_API_BUSINESS_PARTNER_SRV', 'data_platform_api_business_partner_exconf', 'BusinessPartnerGeneral', 'data_platform_business_partner_general_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'ProductionPlant', 'DPFM_API_PLANT_SRV', 'data_platform_api_plant_exconf', 'PlantGeneral', 'data_platform_plant_general_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'ProductionPlantStorageLocation', 'DPFM_API_PLANT_SRV', 'data_platform_api_plant_exconf', 'PlantStorageLocation', 'data_platform_plant_storage_location_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'ProductionPlantBatch', 'DPFM_API_BATCH_MASTER_RECORD_SRV', 'data_platform_api_batch_master_record_exconf', 'Batch', 'data_platform_batch_master_record_batch_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'Incoterms', 'DPFM_API_INCOTERMS_SRV', 'data_platform_api_incoterms_exconf', 'Incoterms', 'data_platform_incoterms_incoterms_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'PaymentTerms', 'DPFM_API_PAYMENT_TERMS_SRV', 'data_platform_api_payment_terms_exconf', 'PaymentTerms', 'data_platform_payment_terms_payment_terms_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'PaymentMethod', 'DPFM_API_PAYMENT_METHOD_SRV', 'data_platform_api_payment_method_exconf', 'PaymentMethod', 'data_platform_payment_method_payment_method_data', 'exconf');
	('ORDERS', 'creates', 'Item', 'Project', 'DPFM_API_PROJECT_SRV', 'data_platform_api_project_exconf', 'Project', 'data_platform_project_project_data', 'exconf');
	('ORDERS', 'creates', 'ItemPricingElement', 'TransactionCurrency', 'DPFM_API_CURRENCY_SRV', 'data_platform_api_currency_exconf', 'Currency', 'data_platform_currency_currency_data', 'exconf');
	('ORDERS', 'creates', 'Partner', 'Organization', 'DPFM_API_ORGANIZATION_SRV', 'data_platform_api_organization_exconf', 'Organization', 'data_platform_organization_organization_data', 'exconf');
	('ORDERS', 'creates', 'Partner', 'Country', 'DPFM_API_COUNTRY_SRV', 'data_platform_api_country_exconf', 'Country', 'data_platform_country_country_data', 'exconf');
	('ORDERS', 'creates', 'Partner', 'Language', 'DPFM_API_LANGUAGE_SRV', 'data_platform_api_language_exconf', 'Language', 'data_platform_language_language_data', 'exconf');
	('ORDERS', 'creates', 'Partner', 'Currency', 'DPFM_API_CURRENCY_SRV', 'data_platform_api_currency_exconf', 'Currency', 'data_platform_currency_currency_data', 'exconf');
	('ORDERS', 'creates', 'Partner', 'AddressID', 'DPFM_API_ADDRESS_SRV', 'data_platform_api_address_exconf', 'data_platform_api_address_exconf_queue', 'Address', 'data_platform_address_address_data', 'exconf');
UNLOCK TABLES;